spring:
  jpa:
    open-in-view: false
    database: default
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: 
    driverClassName: org.h2.Driver
  mail:
    host: fake-host
    port: 587
    protocol: smtp
    username: a@a.com
    password: 