export interface ManagerDetails {
  allowedBalance: number
  arabicAddress: string
  arabicName: string
  billable: boolean
  birthDate: string
  disabled: boolean
  email: string
  endDate: string
  englishAddress: string
  englishName: string
  fullTime: boolean
  id: number
  imgUrl: string
  insuranceDate: string
  isEnabled: boolean
  joiningDate: string
  lastTimePasswordChanged: string
  mobileNumber: string
  nationalId: string
  notPasswordExpired: boolean
  overtime: number
  password: string
  payRate: number
  remainingBalance: number
  requests: []
  resetToken: string
  resigned: boolean
  roles: []
  teams: []
  username: string
  yearsOfInsurance: number
}
